export const PERMISSIONS = {
  DASHBOARD: [],
  USER: ['USER:C', 'USER:R', 'USER:U', 'USER:D'],
  PERMISSION: ['PERMISSION:C', 'PERMISSION:R', 'PERMISSION:U', 'PERMISSION:D'],
  ANNOUNCEMENT: ['ANNOUNCEMENT:C', 'ANNOUNCEMENT:R', 'ANNOUNCEMENT:U', 'ANNOUNCEMENT:D'],
  INVENTORY: ['INVENTORY:C', 'INVENTORY:R', 'INVENTORY:U', 'INVENTORY:D'],
  ORDER: ['ORDER:C', 'ORDER:R', 'ORDER:U', 'ORDER:D'],
  REIMBURSEMENT: ['REIMBURSEMENT:C', 'REIMBURSEMENT:R', 'REIMBURSEMENT:U', 'REIMBURSEMENT:D'],
};
